// ml/train_roommates.mjs — offline trainer/evaluator for the shadow roommates head.
//
// Usage:  node ml/train_roommates.mjs <path-to-export.json>
//
// Writes: lib/ml_roommates_weights.js
//
// Labels come from ROOMMATES_RE, but the text is MASKED so the model cannot
// simply relearn the trigger phrase (see lib/ml_roommates.js for why). The
// evaluation therefore answers a specific question: with the keywords removed,
// can the surrounding register still identify a room-share? A high masked CV
// accuracy means yes — the model is an independent opinion rather than a
// keyword detector — and the disagreement count is the size of the review
// queue shadow mode will hand the user.

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { buildCorpus, trainLR, crossValProbs, exportHead, predictRow, mulberry32 } from '../lib/ml_train_core.js';
import { scoreHead, uniqueTokens } from '../lib/ml_features.js';
import { regexExtractTags } from '../lib/regex_extractor.js';
import { maskRoommateKeywords, ROOMMATES_FEATURE_VERSION } from '../lib/ml_roommates.js';
import { verdictTruth } from '../lib/ml_shadow.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const exportPath = process.argv[2];
if (!exportPath) {
  console.error('Usage: node ml/train_roommates.mjs <path-to-export.json>');
  process.exit(1);
}

const posts = JSON.parse(readFileSync(exportPath, 'utf8'));
const rentals = posts.filter(p =>
  (p.human_label || p.ai_label) === 'rental' && !p.is_duplicate && (p.text || '').trim());

// Label precedence: shadow VERDICT > tags_human_override > keyword regex.
// Never the model's own output — same rule as every other head here. Roommates
// is boolean and never null, so there is no confirmed-absent case to handle
// (unlike price, where a null verdict is itself a meaningful label).
let fromVerdict = 0, fromOverride = 0;
const rows = rentals.map(p => {
  const vt = verdictTruth(p, 'roommates');
  let y;
  if (typeof vt === 'boolean')                        { y = vt; fromVerdict++; }
  else if (typeof p.tags_human_override?.roommates === 'boolean')
                                                      { y = p.tags_human_override.roommates; fromOverride++; }
  else                                                { y = (regexExtractTags(p.text) || {}).roommates; }
  return { raw: p.text, masked: maskRoommateKeywords(p.text), y: y ? 1 : 0 };
});
console.log(`labels from shadow verdicts: ${fromVerdict}, from tag overrides: ${fromOverride}`);
const pos = rows.filter(r => r.y).length;
console.log(`rentals ${rows.length} — roommates=true ${pos}, false ${rows.length - pos}`);

const { vocab, idf, X } = buildCorpus(rows.map(r => r.masked));
const y = rows.map(r => r.y);
console.log(`masked-text vocab: ${vocab.size}`);

// ── how much survives masking? ───────────────────────────────────────────────
const probs = crossValProbs(X, y, vocab.size, 5, 11);
const acc = y.filter((v, i) => (probs[i] >= 0.5 ? 1 : 0) === v).length / y.length;
const posIdx = y.map((v, i) => v ? i : -1).filter(i => i >= 0);
const recall = posIdx.filter(i => probs[i] >= 0.5).length / posIdx.length;
const negIdx = y.map((v, i) => v ? -1 : i).filter(i => i >= 0);
const spec = negIdx.filter(i => probs[i] < 0.5).length / negIdx.length;
console.log(`\nCV on MASKED text — accuracy ${(100 * acc).toFixed(1)}%  ` +
  `recall(true) ${(100 * recall).toFixed(1)}%  specificity(false) ${(100 * spec).toFixed(1)}%`);
console.log('A high score here means the register alone identifies a room-share,');
console.log('i.e. the head is not just re-detecting the keyword it was trained on.');

// Majority-class baseline: what "always false" would score.
console.log(`baseline (always false): ${(100 * (1 - pos / rows.length)).toFixed(1)}%`);

// ── review-queue size: how often will it disagree with the regex? ────────────
console.log('\ndisagreements with the regex (= the review queue shadow mode creates):');
for (const t of [0.5, 0.7, 0.9]) {
  const dis = rows.filter((r, i) => ((probs[i] >= t ? 1 : probs[i] <= 1 - t ? 0 : r.y)) !== r.y).length;
  console.log(`  at confidence ${t}: ${dis} posts (${(100 * dis / rows.length).toFixed(1)}%)`);
}

// ── export ───────────────────────────────────────────────────────────────────
const model = trainLR(X, y, X.map((_, i) => i), mulberry32(23), vocab.size);
const weights = exportHead(model, vocab, idf, 8000);

let flips = 0;
for (let i = 0; i < rows.length; i++) {
  const full = predictRow(model, X[i]) >= 0.5;   // final model, not the CV fold
  const pruned = scoreHead(weights, model.b, uniqueTokens(rows[i].masked)) >= 0.5;
  if (full !== pruned) flips++;
}
console.log(`\npruning check: ${flips}/${rows.length} label flips vs the unpruned model`);

const out = `// lib/ml_roommates_weights.js — GENERATED by ml/train_roommates.mjs. Do not edit by hand.
// Regenerate with:  node ml/train_roommates.mjs <path-to-export.json>
// token: [weight, idf]. Scored by lib/ml_features.js::scoreHead.

export const ML_ROOMMATES_META = {
  roommates_feature_version: ${ROOMMATES_FEATURE_VERSION},
  trained_at: ${JSON.stringify(new Date().toISOString())},
  train_posts: ${rows.length},
  cv_accuracy: ${acc.toFixed(4)},
  masked: true,
};

export const ML_ROOMMATES_BIAS = ${model.b.toFixed(5)};
export const ML_ROOMMATES_WEIGHTS = ${JSON.stringify(weights)};
`;
writeFileSync(join(root, 'lib/ml_roommates_weights.js'), out, 'utf8');
console.log(`wrote lib/ml_roommates_weights.js (${Object.keys(weights).length} tokens)`);
