// lib/ml_classifier.js — in-extension ML layer (runtime side).
//
// Plain-JS logistic-regression heads over TF-IDF features. No network, no
// dependencies; safe to import from the MV3 service worker. Weights are
// generated by ml/train.mjs from ml/gold_labels.json + a dashboard export
// and live in lib/ml_weights.js.
//
// Intended use (wired in the ML-integration stage):
//   - mlHybridLabel(text, regexLabel): the shipped decision rule. The regex
//     label stands unless the model is confident it is wrong. Measured on
//     5-fold CV over the gold set: hybrid ≥ both regex-alone and model-alone
//     on accuracy AND rental-recall (recall matters most — a missed apartment
//     is worse than a spurious alert).
//   - mlBrokerProb(text): broker-fee likelihood learned from keyword-masked
//     weak supervision. Meant for posts where the regex broker extractor
//     returns null; only act on confident values (see BROKER_CONFIDENCE).

import { uniqueTokens, scoreHead } from './ml_features.js';
import {
  ML_META, ML_LABEL_BIAS, ML_LABEL_WEIGHTS, ML_BROKER_BIAS, ML_BROKER_WEIGHTS,
} from './ml_weights.js';

// Model may only override the regex when at least this confident.
// 0.9 chosen on CV: best rental-recall, near-best accuracy, and it stays out
// of the way on posts a human already corrected.
export const ML_CONFIDENCE = 0.9;
export const BROKER_CONFIDENCE = 0.9;

export { ML_META };

/** @returns {{ prob: number, label: 'rental'|'not_rental' }} */
export function mlClassifyPost(text) {
  const prob = scoreHead(ML_LABEL_WEIGHTS, ML_LABEL_BIAS, uniqueTokens(text || ''));
  return { prob, label: prob >= 0.5 ? 'rental' : 'not_rental' };
}

/**
 * The hybrid decision rule: regex label unless the model confidently
 * disagrees. Pass regexLabel=null for posts the regex could not label —
 * then the model's plain label is used regardless of confidence.
 * @returns {{ label: 'rental'|'not_rental', prob: number, overrode: boolean }}
 */
export function mlHybridLabel(text, regexLabel) {
  const { prob, label } = mlClassifyPost(text);
  if (regexLabel == null) return { label, prob, overrode: false };
  const confident = prob >= ML_CONFIDENCE || prob <= 1 - ML_CONFIDENCE;
  if (confident && label !== regexLabel) return { label, prob, overrode: true };
  return { label: regexLabel, prob, overrode: false };
}

/** Broker-fee likelihood in [0,1]. Act only on confident values. */
export function mlBrokerProb(text) {
  return scoreHead(ML_BROKER_WEIGHTS, ML_BROKER_BIAS, uniqueTokens(text || ''));
}

/**
 * Fill-in for the broker tag when the regex returned null:
 * true / false when confident, null otherwise.
 */
export function mlBrokerFill(text) {
  const p = mlBrokerProb(text);
  if (p >= BROKER_CONFIDENCE) return true;
  if (p <= 1 - BROKER_CONFIDENCE) return false;
  return null;
}
