// lib/ml_classifier.js — in-extension ML layer (runtime side).
//
// Plain-JS logistic-regression heads over TF-IDF features. No network, no
// dependencies; safe to import from the MV3 service worker. Bundled weights
// (lib/ml_weights.js, generated by ml/train.mjs) are the fallback; weights
// retrained in-extension (lib/ml_retrain.js) are stored in
// chrome.storage.local and take precedence once loaded — call
// loadStoredMlWeights() at worker startup and after every retrain.
//
// API:
//   - mlHybridLabel(text, regexLabel): the shipped decision rule. The regex
//     label stands unless the model is confident it is wrong. Measured on
//     5-fold CV over the gold set: hybrid ≥ both regex-alone and model-alone
//     on accuracy AND rental-recall (recall matters most — a missed apartment
//     is worse than a spurious alert).
//   - mlBrokerFill(text): broker-fee fill-in learned from keyword-masked weak
//     supervision, for posts where the regex broker extractor returns null.

import { uniqueTokens, scoreHead, FEATURE_VERSION } from './ml_features.js';
import {
  ML_META, ML_LABEL_BIAS, ML_LABEL_WEIGHTS, ML_BROKER_BIAS, ML_BROKER_WEIGHTS,
} from './ml_weights.js';

// Model may only override the regex when at least this confident.
// 0.9 chosen on CV: best rental-recall, near-best accuracy, and it stays out
// of the way on posts a human already corrected.
export const ML_CONFIDENCE = 0.9;
export const BROKER_CONFIDENCE = 0.9;

// Active weights — bundled by default, swapped by loadStoredMlWeights().
let ACTIVE = {
  source: 'bundled',
  meta: ML_META,
  labelW: ML_LABEL_WEIGHTS, labelB: ML_LABEL_BIAS,
  brokerW: ML_BROKER_WEIGHTS, brokerB: ML_BROKER_BIAS,
};

export function activeMlMeta() {
  return { source: ACTIVE.source, ...ACTIVE.meta };
}

// Load retrained weights from chrome.storage.local (key written by
// lib/ml_retrain.js). Ignores stored weights from a different feature
// version — those would be scored with the wrong tokenizer — and degenerate
// payloads trained on too little data (a fresh install once promoted a
// 212-row model that labeled everything rental; the bundled weights are
// always better than that). Threshold mirrors ml_retrain.js::MIN_GOLD_ROWS.
export async function loadStoredMlWeights() {
  if (typeof chrome === 'undefined' || !chrome.storage?.local) return ACTIVE.source;
  try {
    const stored = (await chrome.storage.local.get('ml_weights')).ml_weights;
    const rows = stored?.meta?.gold_rows ?? stored?.meta?.label_rows ?? 0;
    if (stored?.label?.weights &&
        stored.meta?.feature_version === FEATURE_VERSION &&
        rows >= 2000) {
      ACTIVE = {
        source: 'retrained',
        meta: stored.meta,
        labelW: stored.label.weights, labelB: stored.label.bias,
        brokerW: stored.broker.weights, brokerB: stored.broker.bias,
      };
    } else {
      ACTIVE = {
        source: 'bundled',
        meta: ML_META,
        labelW: ML_LABEL_WEIGHTS, labelB: ML_LABEL_BIAS,
        brokerW: ML_BROKER_WEIGHTS, brokerB: ML_BROKER_BIAS,
      };
      if (stored) console.warn(
        `[TLV Rentals] Ignoring stored ML weights (${rows} training rows < 2000) — using bundled weights.`);
    }
  } catch (err) {
    console.warn('[TLV Rentals] Failed to load stored ML weights:', err);
  }
  return ACTIVE.source;
}

/** @returns {{ prob: number, label: 'rental'|'not_rental' }} */
export function mlClassifyPost(text) {
  const prob = scoreHead(ACTIVE.labelW, ACTIVE.labelB, uniqueTokens(text || ''));
  return { prob, label: prob >= 0.5 ? 'rental' : 'not_rental' };
}

/**
 * The hybrid decision rule: regex label unless the model confidently
 * disagrees. Pass regexLabel=null for posts the regex could not label —
 * then the model's plain label is used regardless of confidence.
 * @returns {{ label: 'rental'|'not_rental', prob: number, overrode: boolean }}
 */
export function mlHybridLabel(text, regexLabel) {
  const { prob, label } = mlClassifyPost(text);
  if (regexLabel == null) return { label, prob, overrode: false };
  const confident = prob >= ML_CONFIDENCE || prob <= 1 - ML_CONFIDENCE;
  if (confident && label !== regexLabel) return { label, prob, overrode: true };
  return { label: regexLabel, prob, overrode: false };
}

/** Broker-fee likelihood in [0,1]. Act only on confident values. */
export function mlBrokerProb(text) {
  return scoreHead(ACTIVE.brokerW, ACTIVE.brokerB, uniqueTokens(text || ''));
}

/**
 * Fill-in for the broker tag when the regex returned null:
 * true / false when confident, null otherwise.
 */
export function mlBrokerFill(text) {
  const p = mlBrokerProb(text);
  if (p >= BROKER_CONFIDENCE) return true;
  if (p <= 1 - BROKER_CONFIDENCE) return false;
  return null;
}
